services:
  mongodb:
    image: mongo:7.0
    container_name: task-tracker-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: task_tracker
    volumes:
      - mongodb_data:/data/db
    networks:
      - task-tracker-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend-nodejs
      dockerfile: Dockerfile
    container_name: task-tracker-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/task_tracker?authSource=admin
      - DATABASE_NAME=task_tracker
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - task-tracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend-vanilla
      dockerfile: Dockerfile
    container_name: task-tracker-frontend
    restart: unless-stopped
    ports:
      - "3002:3002"
    depends_on:
      - backend
    networks:
      - task-tracker-network

volumes:
  mongodb_data:

networks:
  task-tracker-network:
    driver: bridge
